---
stages:
- name: Build frontend
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: load_testing
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Test frontend
  inputs:
  - type: job
    stage: Build frontend
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash
      # invoke tests here
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      # Run unit-tests
      npm install && npm run test-unit
    enable_tests: true
    test_file_pattern: test-*.xml
- name: Deploy frontend
  inputs:
  - type: job
    stage: Build frontend
    job: Build
    dir_name: null
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  - name: BLUE_GREEN
    type: text_area
    value: ${DEPLOY_SCRIPT}
  - name: ICON_SERVER_NAME
    type: text
    value: ${ICON_SERVER_NAME}
  - name: HOSTNAMES
    type: text
    value: ${HOSTNAMES}
  - name: FRONT_END_DOMAIN
    type: text
    value: ${FRONT_END_DOMAIN}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash    
      echo "${BLUE_GREEN}" > blue_green.sh
      chmod +x blue_green.sh

      ./blue_green.sh  -f bluemix/base-manifest.yml --no-start --no-route

      for i in $(echo $HOSTNAMES | tr ',' ' ')
      do
        cf map-route ${CF_APP} ${FRONT_END_DOMAIN} --hostname $i
      done

      cf set-env ${CF_APP} ICON_SERVER https://${ICON_SERVER_NAME}.${ICON_DOMAIN}
      cf start ${CF_APP}
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
