---
stages:
- name: Build ICON Kibana
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
- name: Deploy ICON Kibana
  inputs:
  - type: job
    stage: Build ICON Kibana
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      # get certificate
      cf service-key icon-elasticsearch Credential1 | grep ca_certificate_base64 | cut -d ':' -f 2 | tr -d "\", \n"  | base64 --decode > cert.pem
      cf push ${CF_APP} -f bluemix/base-manifest.yml -n ${CF_APP} -d ${ICON_DOMAIN} --no-start
      # set certificate
      cf set-env ${CF_APP} NODE_EXTRA_CA_CERTS cert.pem
      cf start ${CF_APP}
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
